apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/ucloud-load-balancer-type: Inner
    service.beta.kubernetes.io/ucloud-load-balancer-vserver-client-timeout: '0'
    service.beta.kubernetes.io/ucloud-load-balancer-vserver-method: Roundrobin
    service.beta.kubernetes.io/ucloud-load-balancer-vserver-protocol: TCP
  name: thanos-querier
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: thanos-querier
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      containers:
      # thanos querier
      - args: 
        - query 
        - --http-address=0.0.0.0:9090
        - --query.replica-label=replica
        - --store=dnssrv+_grpc._tcp.thanos-receive.monitoring.svc.cluster.local
        name: thanos-querier
        image: registry-team.smzdm.com/prometheus/thanos:v0.18.0
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
      terminationGracePeriodSeconds: 60